### ISSUE TITLE
SD card cannot be accessed

### ISSUE THREAD

**Issue by xebbmw** [stevstrong/SdFat#1]
Hi Steve,

I am having troubles using the library SDFat, maybe you can help me.

I am using your core ARDUINO_STM32 with your SDFat implementation and the example provide at 

https://github.com/stevstrong/SdFat/tree/master/examples/STM32F4SdioDemo. The SDFat library is 

stored into hardware/Arduino_STM32/STM32F4/library/SDFat. At some point after downloading the 

libraries and compiling the sketch I had to comment the following coding inside SdioF4.cpp

```
//uint32_t SdioCard::cardSize(void) {
//  return sdCardCapacity(&m_csd);
//} 
```
otherwise the coding would not compile without errors.

My board is an STM32F407VET mini (vcc-gnd version). 

I followed the threads at 
[libmaple] Generic F407VE mini (vcc-gnd version)
https://web.archive.org/web/20190316170144/https://www.stm32duino.com/viewtopic.php?f=39&t=2804&start=40

and also at 

[libmaple] SDIO
https://web.archive.org/web/20190316162001/http://www.stm32duino.com/viewtopic.php?
f=39&t=2215&start=90

I have tried several SD cards, a 2GB, a 16GB or a 32GB but none of them work, the error message is 
always:

```
######################################################
  Demo sketch of STM32F4 SDIO (DMA) implementation.
######################################################
SdFatSdio begin() failed
Can't access SD card. Do not reformat.
No card, wrong chip select pin, or SPI problem?
SD errorCode: 0X20,0X0
```

I am using SerialUSB as output, the code is uploaded via STM32 ST-LINK. I have connected a TFT LCD to the board, but when testing STM32F4SdioDemo the LCD is not powered nor initialized.

Do you have any clue why the SD card cannot be accessed? Is it something I am doing wrong?

Thanks

**Comment by stevstrong** [comment]
I will check this later in the evening.
I suppose you have selected the right board in the Arduino IDE.
It would be interesting to see the original error message related to card size, too.

**Comment by xebbmw** [comment]
I am using Arduino IDE 1.8.12 and the selected board is Generic STM32F407V mini series.

To further investigate the problem, I enhanced the Setup method from STM32F4SdioDemo sketch with the following:

```
 if (!sd.cardBegin()) {
      sd.initErrorHalt("SdFatSdio cardBegin() failed");
  }
  if (!sd.fsBegin()) {
      sd.initErrorHalt("SdFatSdio fsBegin() failed");
  }   
  if (!sd.begin()) {
      sd.initErrorHalt("SdFatSdio begin() failed");
  }
```
And now the output from SerialUSB looks like this:
```
######################################################
  Demo sketch of STM32F4 SDIO (DMA) implementation.
######################################################
SdFatSdio cardBegin() failed
Can't access SD card. Do not reformat.
No card, wrong chip select pin, or SPI problem?
SD errorCode: 0X20,0X0
```
Is it something I am missing in the initialization of SDIO?

**Comment by stevstrong** [comment]
[This commit in my repo](https://github.com/stevstrong/Arduino_STM32/commit/395126bc737b7fb2a0093ab3aa84d9f744cbfe80) should fix the issue.
This is what I get displayed in serial monitor for the SDIO demo sketch:
```
######################################################
  Demo sketch of STM32F4 SDIO (DMA) implementation.
######################################################

init time: 8 ms

Card type: SD2

Manufacturer ID: 27
OEM ID: PH
Product: SD02G
Version: 3.0
Serial number: 97bdbf7c
Manufacturing date: 8/2011

cardSize: 1969.23 MB (MB = 1,000,000 bytes)
flashEraseSize: 128 blocks
eraseSingleBlock: true
OCR: 80ff8000

Volume is FAT16
blocksPerCluster: 64
clusterCount: 60086
freeClusters: 59651
freeSpace: 1954.64 MB (MB = 1,000,000 bytes)
fatStartBlock: 138
fatCount: 2
blocksPerFat: 235
rootDirStart: 608
dataStartBlock: 640

FreeStack: 62887
######################################################

Type any character to start
```

Please check out again my SdFat repo, too, I have updated it from the origin.

**Comment by stevstrong** [comment]
You should format your cards using [Sd formatter](https://www.sdcard.org/downloads/formatter/) to FAT (not FAT32, this is not supported)

**Comment by stevstrong** [comment]
Update: there is one more file in my repo which had to be fixed, I missed it in the previous commit, so check it out again.
Please test it and let me know if it works for you.

**Comment by xebbmw** [comment]
Still does not work for me. From your master branch I got the new version of SdioF4.cpp and also I replaced the complete SdFat library and copied it to hardware/Arduino_STM32/STM32F4/library/SdFat.

I used the SD Formatter and tried with two cards, 2GB (formatted as FAT16) and 32GB (formatted as FAT32).

After compilation and uploading to MCU, I have the same error as before.

I was looking to eliminate other factors (hardware faults), I removed the wires to other components that I have on the board (TFT). I also checked if SDcard connector gets power (3.3V) and also if wires are connected from SDcard connector to board pins (PC10, PC11, PD2, VCC, PC12, GND, PC8, PC9). The next step would be to check if all this signals go to the correct MCU pins.

The output log that you provided above, is it from the same type of board blue mini STM32F407VET6 or you are using another one? 

Could it be something related to the clock of this board 25Mhz?

**Comment by stevstrong** [comment]
I tested the [blue mini generic F407 board with 25MHz crystal](https://web.archive.org/web/20190316160822/http://wiki.stm32duino.com/index.php?title=Vcc-gnd.com_STM32F407VET6_Mini), which is supposed to be identical with yours.
Do you have any warning or error messages when you build the sketch in Arduino?
You also need [this change](https://github.com/stevstrong/Arduino_STM32/commit/1a8bd07d879c351c9bf8970c3d8093fa235dbeff), too.

**Comment by xebbmw** [comment]
Thanks a lot, Steve!

Now it works, it seems I was missing the latest change from sdio.c file.

This is the output log that I get now:

```
######################################################
  Demo sketch of STM32F4 SDIO (DMA) implementation.
######################################################

init time: 8 ms

Card type: SD2

Manufacturer ID: 2
OEM ID: TM
Product: SA02G
Version: 0.7
Serial number: c6a22e26
Manufacturing date: 10/2011

cardSize: 1948.25 MB (MB = 1,000,000 bytes)
flashEraseSize: 128 blocks
eraseSingleBlock: true
OCR: 80ff8000

Volume is FAT16
blocksPerCluster: 64
clusterCount: 59446
freeClusters: 59444
freeSpace: 1947.86 MB (MB = 1,000,000 bytes)
fatStartBlock: 142
fatCount: 2
blocksPerFat: 233
rootDirStart: 608
dataStartBlock: 640

FreeStack: 62887
######################################################

Type any character to start
```

**Comment by stevstrong** [comment]
Glad to hear that it works.
